- .gitignore
- lib/bigcommerce/lightstep/rails_controller_instrumentation.rb
- lib/bigcommerce/lightstep/tracer.rb
- lib/bigcommerce/lightstep/transport.rb
* Make sure spans are finished and current span is reset if the measured
block throws an error.
* Set tag `error = true` on exceptions in measured code
* Set more reasonable timeouts on Lightstep connections
* Fix a couple of linting errors.
> PEN-929: Add error handling

- .rubocop.yml
- .rubocop_todo.yml
- CHANGELOG.md
- lib/bigcommerce/lightstep/tracer.rb
This fixes the case where the `Bigcommerce::Lightstep.configure` method is never called in a service, but `Bigcommerce::Lightstep.start_span` is, which triggers an issue in the underlying lightstep gem where it attempts to disable the reporter (which isn't set yet) and calls `flush` on `nil`.
----
@bigcommerce/platform-engineering
> Handle issue that occurs if lightstep is disabled but the start_span method is still called

- CHANGELOG.md
- README.md
- bc-lightstep-ruby.gemspec
- lib/bigcommerce/lightstep.rb
- lib/bigcommerce/lightstep/configuration.rb
- lib/bigcommerce/lightstep/middleware/faraday.rb
- spec/bigcommerce/lightstep_spec.rb
- Adds LIGHTSTEP_MAX_BUFFERED_SPANS config ENV + setting for maximum number of spans to buffer
- Adds LIGHTSTEP_MAX_LOG_RECORDS config ENV + setting for maximum number of log records that can be on a span
- Adds LIGHTSTEP_MAX_REPORTING_INTERVAL_SECONDS config ENV + setting for max reporting flush interval to collector
Bumps lightstep gem to 0.13.0.
Tested on a few various services, spans come in as expected, can successfully adjust reporting periods.
----
@bigcommerce/platform-engineering @pedelman @zackangelo @zvuki
> PEN-975: Add configuration around reporting options

- .travis.yml
- CHANGELOG.md
- lib/bigcommerce/lightstep/middleware/faraday.rb
- lib/bigcommerce/lightstep/rails_controller_instrumentation.rb
When using the `RailsControllerInstrumentation` module, if the reporter is uninitialized (which can happen in test suites, for example), and an exception occurs in a controller, bc-lightstep-ruby will currently 500 with a NoMethodError. 
This is due to a missed check in lightstep-tracer-ruby's Span class where it is not checking for the presence of the `@reporter` instance variable before calling `add_span` on it. In order to mitigate against this, we should first check to ensure the reporter is initialized before attempting to finish the span. We do a similar approach in the normal add_span calls elsewhere.
----
@bigcommerce/platform-engineering @jmwiese
> PEN-1088: Fix issue where unitialized reporters can cause a NoMethodError

- .travis.yml
- CHANGELOG.md
- README.md
- lib/bigcommerce/lightstep/transport.rb
- spec/bigcommerce/lightstep/transport_spec.rb
Allows usage of blank access tokens,  which can be used with satellites that have disabled token checking and are using project-specific keys.
----
@bigcommerce/platform-engineering
> PEN-1135: Allow for usage of blank access tokens

- .rubocop_todo.yml
- .travis.sh
- CHANGELOG.md
- lib/bigcommerce/lightstep.rb
- lib/bigcommerce/lightstep/redis/tracer.rb
- lib/bigcommerce/lightstep/redis/wrapper.rb
- spec/bigcommerce/lightstep/redis/tracer_spec.rb
- spec/support/mock_tracer.rb
Adds the ability to span redis timings for all redis commands. Adds as tags the host, port, db, and the command being logged (but not the args).
----
@bigcommerce/ruby @bigcommerce/platform-engineering
> feat(platform): PEN-1139 - Adds ability to span redis timings

- CHANGELOG.md
- bc-lightstep-ruby.gemspec
chore(PBY-616): updates Gemspec to allow for newer versions of faraday gem
* Reviewed the change log for the Faraday gem here:
https://github.com/lostisland/faraday/releases
* Updated to use Faraday 0.15.4 and all specs pass
> Updates gemspec to allow for newer versions of faraday gem

- CHANGELOG.md
- lib/bigcommerce/lightstep/interceptors/env.rb
- spec/bigcommerce/lightstep/interceptors/env_spec.rb
Adds a new preset for injecting the container hostname globally into spans.
----
@jmwiese @bigcommerce/platform-engineering @bigcommerce/ruby
> Add `hostname` preset for env var injection into spans

- CHANGELOG.md
- README.md
- lib/bigcommerce/lightstep/rspec.rb
Adds a custom rspec matcher that can be used by services to easily test for custom spans.
```ruby
expect { my_code_here }.to create_a_lightstep_span(name: 'my-span-name', tags: { tag_one: 'value-here' })
```
----
@bigcommerce/platform-engineering @jmwiese @bigcommerce/ruby
> Add create_a_lightstep_span rspec matcher

- CHANGELOG.md
- README.md
- lib/bigcommerce/lightstep/interceptors/env.rb
- lib/bigcommerce/lightstep/interceptors/registry.rb
- spec/bigcommerce/lightstep/interceptors/env_spec.rb
The ENV interceptor is currently collecting and parsing values from ENV per-span. This changes it to only collect and parse the values during initialization, and only add the tags to the span in the actual span block.
----
@bigcommerce/platform-engineering @jmwiese @pedelman @mattolson
> Pre-materialize tag values for ENV interceptor at initialization to reduce CPU usage per-span

- CHANGELOG.md
- lib/bigcommerce/lightstep/interceptors/env.rb
- spec/bigcommerce/lightstep/interceptors/env_spec.rb
Adds two new env vars for the nomad ENV span injection interceptor:
* `NOMAD_NODE_ID`
* `NOMAD_NODE_NAME`
This allows tracking performance per nomad client.
----
@bigcommerce/platform-engineering @jmwiese @zvuki
> Add NOMAD_NODE_ID, NOMAD_NODE_NAME as lightstep span tags

- CHANGELOG.md
- README.md
- bc-lightstep-ruby.gemspec
- lib/bigcommerce/lightstep.rb
- lib/bigcommerce/lightstep/active_record/adapter.rb
- lib/bigcommerce/lightstep/active_record/tracer.rb
- lib/bigcommerce/lightstep/configuration.rb
- lib/bigcommerce/lightstep/transport_factory.rb
- lib/bigcommerce/lightstep/version.rb
- spec/bigcommerce/lightstep/active_record/tracer_spec.rb
* Adds automatic mysql span tracing for ActiveRecord
* Adds missing ENV vars for configuration of various other elements
* Clarify explicit dependency on active_support
* More clearly documents README for above
----
@bigcommerce/ruby @bigcommerce/platform-engineering @jmwiese
> Add automatic ActiveRecord mysql span tracing

- CHANGELOG.md
- spec/bigcommerce/lightstep/active_record/tracer_spec.rb
Related to https://github.com/bigcommerce/gruf-lightstep/pull/15 - The current error tag addition when rescuing StandardError in the tracer prevents upstream libraries from handling errors their own way. This causes issues when wanting to conditionally flag different types of exceptions as errors (say, GRPC status codes). This fixes this by only setting the error tag if it is not already set.
---
@bigcommerce/platform-engineering @bigcommerce/ruby
> Only set error tag if not already set

- .circleci/config.yml
- CHANGELOG.md
- bc-lightstep-ruby.gemspec
- lib/bigcommerce/lightstep/tracer.rb
- spec/bigcommerce/lightstep/tracer_spec.rb
This fixes some of the issues where we've seen in LightStep's 0.16 release: 
``` 
undefined method `extract' for nil:NilClass\n/opt/ruby2.6/lib/ruby/gems/2.6.0/gems/lightstep-0.16.0/lib/lightstep/tracer.rb:210
```
by adding sufficient guards when LightStep is not initialized, but start_span has been called.
---
@bigcommerce/ruby
> Fix issue where parent span determination can be nil if lightstep is not initialized

- CHANGELOG.md
- bc-lightstep-ruby.gemspec
This allows other apps a more seamless transition to update Faraday. This library only uses Faraday for middleware support, which transitive dependencies should handle fine.
---
@bigcommerce/ruby @bigcommerce/oss-maintainers
> Relax pin on faraday

- CHANGELOG.md
- README.md
- lib/bigcommerce/lightstep/traceable.rb
- lib/bigcommerce/lightstep/version.rb
- spec/bigcommerce/lightstep/traceable_spec.rb
- spec/support/traceable.rb
Adds the ability to add a span to any method via a Traceable module and `trace` class method:
```ruby
class MyService
include ::Bigcommerce::Lightstep::Traceable
trace :call, 'operation.do-my-thing' do |span:, product:, options:|
span.set_tag('store_id', request.store_id)
end
trace :call, 'operation.do-my-thing'
def call(product:, options:)
end
end
```
> Add `::Bigcommerce::Lightstep::Traceable` module for tracing individual methods

- CHANGELOG.md
- README.md
- lib/bigcommerce/lightstep/traceable.rb
- spec/bigcommerce/lightstep/traceable_spec.rb
- spec/support/traceable.rb
The trace method introduced in #36 does not support tracing positional argument methods. This adds support for it, with a slight caveat around single-hash-argument positional methods.
rspec, manually
> Support positional argument methods when using the `Traceable` trace method

- CHANGELOG.md
- lib/bigcommerce/lightstep/active_record/adapter.rb
Handle the new ActiveRecord interfaces in Rails 7 with the ActiveRecord instrumentor.
Put this on a Rails 7 repository, works as expected:
```
active_record_connection_pool_connections{pool_name="primary",pid="79850"} 0
active_record_connection_pool_busy{pool_name="primary",pid="79850"} 0
active_record_connection_pool_dead{pool_name="primary",pid="79850"} 0
active_record_connection_pool_idle{pool_name="primary",pid="79850"} 0
active_record_connection_pool_waiting{pool_name="primary",pid="79850"} 0
active_record_connection_pool_size{pool_name="primary",pid="79850"} 16
```
> Add support for ActiveRecord 7

- lib/bigcommerce/lightstep/rails_controller_instrumentation.rb
Provide a hook for controllers to specify additional span tags.
Tested it on a controller which uses the instrumentation trace
```ruby
def lightstep_additional_span_tags
{
store_id: params[:store_id]
}
end
```
> Provide a hook for controllers to pass additional span tags

- .circleci/config.yml
- CHANGELOG.md
- Gemfile
- bc-lightstep-ruby.gemspec
- lib/bigcommerce/lightstep/configuration.rb
- lib/bigcommerce/lightstep/redis/wrapper.rb
This gem does not support Redis 5.x; drop support for it and encourage moving to the OpenTelemetry provided ruby libraries over this gem.
Also add Ruby 3.3 test suite.
`bundle exec rspec`, as well as this PR.
> Do not instrument redis 5.x in this library for compatibility reasons

- .github/PULL_REQUEST_TEMPLATE.md
Updates PR template to standard template. See https://docs.dev.bigcommerce.net/process/repositories/pull-request-templates.html
Revert this PR.
This PR tests it, essentially.
[ENGP-245]: https://bigcommercecloud.atlassian.net/browse/ENGP-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENGP-245: Update PR template to standard tpl

- .circleci/config.yml
- .rubocop.yml
- CHANGELOG.md
- Gemfile
- bc-lightstep-ruby.gemspec
- lib/bigcommerce/lightstep/interceptors/env.rb
- lib/bigcommerce/lightstep/interceptors/registry.rb
* Add support for Ruby 3.4
* Drop support for Ruby 3.0, 3.1
Revert.
Unit suite should pass.
> Add Ruby 3.4 support, drop Ruby 3.0, 3.1
